spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: 'false'
  application:
    name: url_shortner
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/url_shortner_local

server:
  port: 8000
